// Generated by pdfx init.
// See: https://pdfx.akashpise.dev/installation#theming
//
// This module is the single source of truth for PDFX styling tokens.
// Update the exported `theme` object to customize component styles.

// Theme type

interface PdfxTheme {
  name: string;
  primitives: {
    typography: Record<string, number>;
    spacing: Record<string | number, number>;
    fontWeights: { regular: number; medium: number; semibold: number; bold: number };
    lineHeights: { tight: number; normal: number; relaxed: number };
    borderRadius: { none: number; sm: number; md: number; lg: number; full: number };
    letterSpacing: { tight: number; normal: number; wide: number; wider: number };
  };
  colors: {
    foreground: string;
    background: string;
    muted: string;
    mutedForeground: string;
    primary: string;
    primaryForeground: string;
    border: string;
    accent: string;
    destructive: string;
    success: string;
    warning: string;
    info: string;
  };
  typography: {
    body: { fontFamily: string; fontSize: number; lineHeight: number };
    heading: {
      fontFamily: string;
      fontWeight: number;
      lineHeight: number;
      fontSize: { h1: number; h2: number; h3: number; h4: number; h5: number; h6: number };
    };
  };
  spacing: {
    page: { marginTop: number; marginRight: number; marginBottom: number; marginLeft: number };
    sectionGap: number;
    paragraphGap: number;
    componentGap: number;
  };
  page: {
    size: 'A4' | 'LETTER' | 'LEGAL';
    orientation: 'portrait' | 'landscape';
  };
  brand?: {
    logo?: string;
    logoWidth?: number;
    logoHeight?: number;
    siteUrl?: string;
    supportEmail?: string;
  };
}

// Theme values

export const theme: PdfxTheme = {
  name: 'terracode-dark',

  // Primitive scales.
  primitives: {
    typography: {
      xs: 9,
      sm: 11,
      base: 14,
      lg: 17,
      xl: 21,
      '2xl': 27,
      '3xl': 35,
    },
    spacing: {
      0: 0,
      0.5: 2,
      1: 4,
      2: 8,
      3: 12,
      4: 16,
      5: 20,
      6: 24,
      8: 32,
      10: 40,
      12: 48,
      16: 64,
    },
    fontWeights: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    lineHeights: {
      tight: 1.15,
      normal: 1.4,
      relaxed: 1.6,
    },
    borderRadius: {
      none: 0,
      sm: 4,
      md: 8,
      lg: 12,
      full: 9999,
    },
    letterSpacing: {
      tight: -0.015,
      normal: 0,
      wide: 0.025,
      wider: 0.05,
    },
  },

  // Semantic colors. Values must be valid for react-pdf.
  colors: {
    foreground: '#fffbeb', // amber-50
    background: '#0a0a0a', // very dark primary background
    muted: '#171717', // neutral-900 equivalent for containers
    mutedForeground: '#94a3b8', // slate-400
    primary: '#FDA10A', // Brand orange
    primaryForeground: '#000000',
    border: '#262626', // neutral-800
    accent: '#FDA10A',
    destructive: '#ef4444',
    success: '#22c55e',
    warning: '#f59e0b',
    info: '#3b82f6',
  },

  // Typography defaults.
  typography: {
    body: {
      fontFamily: 'Helvetica',
      fontSize: 10,
      lineHeight: 1.5,
    },
    heading: {
      fontFamily: 'Helvetica-Bold',
      fontWeight: 700,
      lineHeight: 1.2,
      fontSize: {
        h1: 30,
        h2: 22,
        h3: 18,
        h4: 15,
        h5: 13,
        h6: 11,
      },
    },
  },

  // Layout spacing.
  spacing: {
    page: {
      marginTop: 56,
      marginRight: 48,
      marginBottom: 56,
      marginLeft: 48,
    },
    sectionGap: 28,
    paragraphGap: 10,
    componentGap: 14,
  },

  // Page defaults.
  page: {
    size: 'A4',
    orientation: 'portrait',
  },

  // Brand identity.
  brand: {
    logo: '/Logo21.png',
    logoWidth: 80,
    logoHeight: 40,
    siteUrl: 'www.terracode.lk',
    supportEmail: 'support@terracode.lk',
  },
};
